services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "8080:8080"
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "8001:5000"