# specify a base image
FROM python:3.10-slim

# switch to working directory
WORKDIR /python-docker

#copy requirements.txt file
COPY requirements_cpu.txt requirements.txt

#install libraries
RUN pip3 install -r requirements.txt

#create folder structure with needed files
COPY deep_learning/main_model/models.py  deep_learning/main_model/models.py
COPY trained_models/flowers_generator_final  trained_models/flowers_generator_final

#copy the server code itself
COPY backend  backend

#run flask as module specifying path to app.pu and host
CMD [ "python3", "-m" , "flask", "--app", "backend/app", "run", "--host=0.0.0.0"]
